# monitoring/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'rag-system'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # RAG Pipeline metrics
  - job_name: 'rag-pipeline'
    static_configs:
      - targets: ['rag-pipeline:8001']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'rag_system_.*'
        action: keep

  # RAG Interface metrics
  - job_name: 'rag-interface'
    static_configs:
      - targets: ['rag-interface:8002']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'rag_system_.*'
        action: keep

  # PostgreSQL exporter (optional)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Node exporter for system metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']